modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"

[[mods]]
modId = "uberminer2"
version = "${file.jarVersion}"
displayName = "Uber Miner 2"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/victorbrndls/UberMiner2"
logoFile = "logo.jpg"
credits = "Thanks :)"
authors = "VictorBrndls"
description = '''
Mining doesn't have to be boring.
'''

[[dependencies.uberminer2]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.uberminer2]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"
